name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress test
      - name: Change directory
        run: cd ./02-desafio-coffee-delivery && ls
        
      # - name: Cypress run
      #   uses: cypress-io/github-action@v5
      #   with:
      #     build: npm run build
      #     start: npm start
      - name: console log
        run: ls
