name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress test
      - name: Change directory
        run: cd ./02-desafio-coffee-delivery && npm install && npm run dev && npx cypress run -y
